# Generated by Django 3.1.7 on 2025-08-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20250827_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='cost_price',
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
    ]
