# Generated by Django 5.0 on 2025-11-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0012_auto_20250830_0313"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicedetail",
            name="cost_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="invoicedetail",
            name="selling_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="invoicedetail",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
